#!/bin/bash
#============================================================
# System Information Script
# Devops Internship - Week 1
#============================================================


echo "======================================================"
echo "         SYSTEM INFORMATION REPORT                    "
echo "======================================================"
echo ""

# Date and Time
echo "Date & Time: $(date)"
echo ""

# System Identity
echo "--- SYSTEM ---"
echo "Hostname: $(hostname)"
echo "OS: $(lsb_release -d | cut -f2)"
echo "kernel: $(uname  -r)"
echo "Architecture: $(uname -m)"
echo ""

# Current User
echo "---USER---"
echo "Current User: $(whoami)"
echo "Home Dir: $HOME"
echo "Shell: $SHELL"
echo ""

# CPU Information
echo "---CPU---"
echo "CPU Model: $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)"
echo "CPI Cores: $(nproc)"

# Memory Information
echo "---MEMORY---"
free -h | grep -E "Mem|Swap"|awk '{printf"%-8s Total: %s Used: %s Free: %s\n", $1, $2, $3, $4}'
echo ""

# Disk Usage
echo "---DISK"""
df -h / | tail -1 | awk '{printf"Root Disk: %s total, %s used (%s), %s available\n", $2, $3, $5, $4}'
echo ""

# Network Interfaces
echo "---NETWORk---"
ip addr show | grep "inet" | awk '{print"IP Address:", $2}'
echo ""

# Top 5 Processes by Memory
echo "---TOP 5 PROCESSES (by memory) ---"
ps aux --sort=-%mem | head -6 | awk '{printf"%-8s %5s%% %s\n", $1, $4, $11}' | head -6
echo ""

echo "================================================="
echo "                  END OF REPORT                 "
echo "================================================="
